### PR TITLE
expanding subnetwork_cidr_suffix

### PR DESCRIPTION
**Pull request by ighosh98**
### Submission Checklist

Increasing subnetwork_cidr_suffix to avoid IP_SPACE_EXHAUSTED errors. Integration tests passed successfully.

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cluster Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Review by annuay-google — APPROVED** [review]
LGTM

**Review by ankitkinra — COMMENTED** [review]
Can you add a comment to blueprint explaining how many pods can this support  ?

**Comment by ighosh98** [comment]
> Can you add a comment to blueprint explaining how many pods can this support ?

should it be nodes? something like: `the subnet can hold 2^(32-20) = 4096 nodes`

**Comment by ankitkinra** [comment]
> > Can you add a comment to blueprint explaining how many pods can this support ?
> 
> should it be nodes? something like: `the subnet can hold 2^(32-20) = 4096 nodes`
Yes let's add it can support 4k nodes (we can skip the exact number)

**Review by ankitkinra — APPROVED** [review]

**Pull request merged**
