### PR TITLE
fix passing additional networks to login nodes

### PR DESCRIPTION
**Pull request by wiktorn**
Adds passing of additional networks to login nodes.

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cluster Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Review by mr0re1 — APPROVED** [review]

**Comment by mr0re1** [comment]
Why do we need this on instance if template already got additional networks?

**Comment by wiktorn** [comment]
Let me double check that

**Comment by wiktorn** [comment]
We need that because in [_slurm_instance](https://github.com/GoogleCloudPlatform/slurm-gcp/blob/master/terraform/slurm_cluster/modules/_slurm_instance/main.tf) we are always providing the `network_interface` section. This overwrites interfaces defined in the template, due to that fact, currently additional interfaces do not work for login instances (i.e. template has 2 interfaces, but instance only one assigned).

**Comment by mr0re1** [comment]
> We need that because in [_slurm_instance](https://github.com/GoogleCloudPlatform/slurm-gcp/blob/master/terraform/slurm_cluster/modules/_slurm_instance/main.tf) we are always providing the `network_interface` section. This overwrites interfaces defined in the template, due to that fact, currently additional interfaces do not work for login instances (i.e. template has 2 interfaces, but instance only one assigned).

Thank you @wiktorn, that is great reason!) It would make sense to stop supplying `additional_networks` to the template (to simplify TF graph at least). WDYT?

Could you please address that and I will run set of integration tests before landing.

**Comment by wiktorn** [comment]
> Thank you @wiktorn, that is great reason!) It would make sense to stop supplying `additional_networks` to the template (to simplify TF graph at least). WDYT?
> 
> Could you please address that and I will run set of integration tests before landing.
Done, works good. Ready to run integration tests.

**Review by mr0re1 — APPROVED** [review]

**Pull request merged**
