### PR TITLE
Update gke-cluster module addon-config for enabling parallelstrore csi driver

### PR DESCRIPTION
**Pull request by mohitchaurasia91**
Triggered PR test for all blueprints with usage of `gke-cluster` module completed with `OK` status.

### Submission Checklist

NOTE: Community submissions can take up to 2 weeks to be reviewed.

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cluster Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

### CODE REVIEW

**Review by annuay-google — APPROVED** [review]
LGTM. Can you see what the difference in apply time looks like as well? AFAIK, the null resource approach took an extra 20-30 min after the cluster was provisioned. (Just curious, this is totally non blocking)

**Comment by annuay-google** [comment]
Also, please wait on the terraform version bump up before merge

**Comment by mohitchaurasia91** [comment]
> LGTM. Can you see what the difference in apply time looks like as well? AFAIK, the null resource approach took an extra 20-30 min after the cluster was provisioned. (Just curious, this is totally non blocking)

yeah, there is a diff observed in `gke-storage-parallelstore` integration test time, its now taking [~48 mins](https://pantheon.corp.google.com/cloud-build/builds/ba80c821-c2d7-458f-9a12-e9f65bb64157?project=hpc-toolkit-dev&e=13803378&mods=logs_tg_prod,trace_api_staging), previously used to take above [~70 mins](https://pantheon.corp.google.com/cloud-build/builds;region=global/9d85ef2b-c13d-48b7-a46c-b8cf13b5d6cb?e=13803378&mods=logs_tg_prod,trace_api_staging&project=hpc-toolkit-dev)

**Comment by mohitchaurasia91** [comment]
> Also, please wait on the terraform version bump up before merge
should be good to merge, as terraform `google` provider version bump PR #3356 is merged

**Pull request merged**
